// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGtgRHQW3Op-pIpEg2IscBeNxkQ_hyUg0',
    appId: '1:725297483957:ios:79d6852788471cb600eefc',
    messagingSenderId: '725297483957',
    projectId: 'npjn-queue-system-jkr',
    storageBucket: 'npjn-queue-system-jkr.firebasestorage.app',
    iosBundleId: 'com.example.queueTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGtgRHQW3Op-pIpEg2IscBeNxkQ_hyUg0',
    appId: '1:725297483957:ios:79d6852788471cb600eefc',
    messagingSenderId: '725297483957',
    projectId: 'npjn-queue-system-jkr',
    storageBucket: 'npjn-queue-system-jkr.firebasestorage.app',
    iosBundleId: 'com.example.queueTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBY1pcBbfB_zspERhnU0KwUwkFAtnqCKs',
    appId: '1:725297483957:web:5dd8bd0b21b4eb4300eefc',
    messagingSenderId: '725297483957',
    projectId: 'npjn-queue-system-jkr',
    authDomain: 'npjn-queue-system-jkr.firebaseapp.com',
    storageBucket: 'npjn-queue-system-jkr.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBY1pcBbfB_zspERhnU0KwUwkFAtnqCKs',
    appId: '1:725297483957:web:5dd8bd0b21b4eb4300eefc',
    messagingSenderId: '725297483957',
    projectId: 'npjn-queue-system-jkr',
    authDomain: 'npjn-queue-system-jkr.firebaseapp.com',
    storageBucket: 'npjn-queue-system-jkr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwEDKsjPo1iWfD-lEwYAP5EdXCDUAmZH4',
    appId: '1:725297483957:android:4375108c2532e45c00eefc',
    messagingSenderId: '725297483957',
    projectId: 'npjn-queue-system-jkr',
    storageBucket: 'npjn-queue-system-jkr.firebasestorage.app',
  );

}