// PSGC-based barangay snapshot for the seven Albay locations supported
// by appointment booking. Kept local so the dropdown works offline.
const Map<String, List<String>> albayThirdDistrictBarangays = {
  "Ligao": [
    "Abella",
    "Allang",
    "Amtic",
    "Bacong",
    "Bagumbayan",
    "Balanac",
    "Baligang",
    "Barayong",
    "Basag",
    "Batang",
    "Bay",
    "Binanowan",
    "Binatagan",
    "Bobonsuran",
    "Bonga",
    "Busac",
    "Busay",
    "Cabarian",
    "Calzada",
    "Catburawan",
    "Cavasi",
    "Culliat",
    "Dunao",
    "Francia",
    "Guilid",
    "Herrera",
    "Layon",
    "Macalidong",
    "Mahaba",
    "Malama",
    "Maonon",
    "Nabonton",
    "Nasisi",
    "Oma-oma",
    "Palapas",
    "Pandan",
    "Paulba",
    "Paulog",
    "Pinamaniquian",
    "Pinit",
    "Ranao-ranao",
    "San Vicente",
    "Santa Cruz",
    "Tagpo",
    "Tambo",
    "Tandarura",
    "Tastas",
    "Tinago",
    "Tinampo",
    "Tiongson",
    "Tomolin",
    "Tuburan",
    "Tula-tula Grande",
    "Tula-tula Pequeño",
    "Tupas",
  ],
  "Guinobatan": [
    "Agpay",
    "Balite",
    "Banao",
    "Batbat",
    "Binogsacan Lower",
    "Binogsacan Upper",
    "Bololo",
    "Bubulusan",
    "Calzada",
    "Catomag",
    "Doña Mercedes",
    "Doña Tomasa",
    "Ilawod",
    "Inamnan Grande",
    "Inamnan Pequeño",
    "Inascan",
    "Iraya",
    "Lomacao",
    "Maguiron",
    "Maipon",
    "Malabnig",
    "Malipo",
    "Malobago",
    "Maninila",
    "Mapaco",
    "Marcial O. Rañola",
    "Masarawag",
    "Mauraro",
    "Minto",
    "Morera",
    "Muladbucad Grande",
    "Muladbucad Pequeño",
    "Ongo",
    "Palanas",
    "Poblacion",
    "Pood",
    "Quibongbongan",
    "Quitago",
    "San Francisco",
    "San Jose",
    "San Rafael",
    "Sinungtan",
    "Tandarora",
    "Travesia",
  ],
  "Jovellar": [
    "Aurora Pob.",
    "Bagacay",
    "Bautista",
    "Cabraran",
    "Calzada Pob.",
    "Del Rosario",
    "Estrella",
    "Florista",
    "Mabini Pob.",
    "Magsaysay Pob",
    "Mamlad",
    "Maogog",
    "Mercado Pob.",
    "Plaza Pob.",
    "Quitinday Pob.",
    "Rizal Pob.",
    "Salvacion",
    "San Isidro",
    "San Roque",
    "San Vicente",
    "Sinagaran",
    "Villa Paz",
    "White Deer Pob.",
  ],
  "Libon": [
    "Alongong",
    "Apud",
    "Bacolod",
    "Bariw",
    "Bonbon",
    "Buga",
    "Bulusan",
    "Burabod",
    "Caguscos",
    "East Carisac",
    "Harigue",
    "Libtong",
    "Linao",
    "Mabayawas",
    "Macabugos",
    "Magallang",
    "Malabiga",
    "Marayag",
    "Matara",
    "Molosbolos",
    "Natasan",
    "Niño Jesus",
    "Nogpo",
    "Pantao",
    "Rawis",
    "Sagrada Familia",
    "Salvacion",
    "Sampongan",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Pascual",
    "San Ramon",
    "San Vicente",
    "Santa Cruz",
    "Talin-talin",
    "Tambo",
    "Villa Petrona",
    "West Carisac",
    "Zone I",
    "Zone II",
    "Zone III",
    "Zone IV",
    "Zone V",
    "Zone VI",
    "Zone VII",
  ],
  "Oas": [
    "Badbad",
    "Badian",
    "Bagsa",
    "Bagumbayan",
    "Balogo",
    "Banao",
    "Bangiawon",
    "Bogtong",
    "Bongoran",
    "Busac",
    "Cadawag",
    "Cagmanaba",
    "Calaguimit",
    "Calpi",
    "Calzada",
    "Camagong",
    "Casinagan",
    "Centro Poblacion",
    "Coliat",
    "Del Rosario",
    "Gumabao",
    "Ilaor Norte",
    "Ilaor Sur",
    "Iraya Norte",
    "Iraya Sur",
    "Manga",
    "Maporong",
    "Maramba",
    "Matambo",
    "Mayag",
    "Mayao",
    "Moroponros",
    "Nagas",
    "Obaliw-Rinas",
    "Pistola",
    "Ramay",
    "Rizal",
    "Saban",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Miguel",
    "San Pascual",
    "San Ramon",
    "San Vicente",
    "Tablon",
    "Talisay",
    "Talongog",
    "Tapel",
    "Tobgon",
    "Tobog",
  ],
  "Pio Duran": [
    "Agol",
    "Alabangpuro",
    "Banawan",
    "Barangay I",
    "Barangay II",
    "Barangay III",
    "Barangay IV",
    "Barangay V",
    "Basicao Coastal",
    "Basicao Interior",
    "Binodegahan",
    "Buenavista",
    "Buyo",
    "Caratagan",
    "Cuyaoyao",
    "Flores",
    "La Medalla",
    "Lawinon",
    "Macasitas",
    "Malapay",
    "Malidong",
    "Mamlad",
    "Marigondon",
    "Matanglad",
    "Nablangbulod",
    "Oringon",
    "Palapas",
    "Panganiran",
    "Rawis",
    "Salvacion",
    "Santo Cristo",
    "Sukip",
    "Tibabo",
  ],
  "Polangui": [
    "Agos",
    "Alnay",
    "Alomon",
    "Amoguis",
    "Anopol",
    "Apad",
    "Balaba",
    "Balangibang",
    "Balinad",
    "Basud",
    "Binagbangan",
    "Buyo",
    "Centro Occidental",
    "Centro Oriental",
    "Cepres",
    "Cotmon",
    "Cotnogan",
    "Danao",
    "Gabon",
    "Gamot",
    "Itaran",
    "Kinale",
    "Kinuartilan",
    "La Medalla",
    "La Purisima",
    "Lanigay",
    "Lidong",
    "Lourdes",
    "Magpanambo",
    "Magurang",
    "Matacon",
    "Maynaga",
    "Maysua",
    "Mendez",
    "Napo",
    "Pinagdapugan",
    "Ponso",
    "Salvacion",
    "San Roque",
    "Santa Cruz",
    "Santa Teresita",
    "Santicon",
    "Sugcad",
    "Ubaliw",
  ],
};

List<String> getBarangaysForMunicipality(String municipality) {
  return albayThirdDistrictBarangays[municipality] ?? const [];
}
